version: '3'

services:
  nginx:
    build: requirements/nginx
    container_name: my-nginx-container
    ports:
      - "443:443"
    networks:
      - backend
    restart: always

  mariadb:
    build: requirements/mariadb
    container_name: my-mariadb-container
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend
    restart: always
    env_file: .env