version: '3'

services:
  nginx:
    image: nginx:$TAG
    build: requirements/nginx
    container_name: nginx
    ports:
      - "443:443"
    depends_on:
      - wordpress
    networks:
      - frontend
    volumes:
      - wp_data:/var/www/html/wordpress
    restart: always
    env_file: .env

  mariadb:
    image: mariadb:$TAG
    build: requirements/mariadb
    container_name: mariadb
    ports:
      - "3306:3306"
    networks:
      - backend
    volumes:
      - db_data:/var/lib/mysql
    restart: always
    env_file: .env

  wordpress:
    image: wordpress:$TAG
    build: requirements/mariadb
    container_name: wordpress
    ports:
      - "9000:9000"
    depends_on:
      - mariadb
    networks:
      - backend
      - frontend
    volumes:
      - wp_data:/var/www/html/wordpress
    restart: always
    env_file: .env

networks:
  backend:
  frontend:

volumes:
  db_data:
  wp_data:
